import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  candidSidebar: [{ type: 'autogenerated', dirName: 'candid' }],
  rustSidebar: [{ type: 'autogenerated', dirName: 'rust' }],
};

export default sidebars;
